version: "2.4"
services:
  jupyter-lab:
    image: "f2forest/tensorflow:latest"
    user: root
    ports:
      - "8888:8888"
    working_dir: /root
    volumes:
      - ./:/root
      - ~/.keras:/root/.keras
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    command: jupyter lab --ip=0.0.0.0 --allow-root
